name: Test and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run tests
      run: |
        docker build -t tiny-dag-tests -f Dockerfile_test .
        docker run tiny-dag-tests

    - name: Push to main if tests pass
      if: ${{ success() }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
