FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN python -m pip install tiny-dag

WORKDIR /app
COPY src/tests/test_graph.py /app

CMD ["sh", "-c", "PARALLEL=True python test_graph.py && PARALLEL=False python test_graph.py"]